# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tidc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tidc.proto',
  package='thermalImagingDataCollect',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntidc.proto\x12\x19thermalImagingDataCollect\"/\n ThermalImagingDataCollectRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\"k\n\x1eThermalImagingDataCollectReply\x12\x33\n\x05mdata\x18\x01 \x03(\x0b\x32$.thermalImagingDataCollect.ModelData\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x01(\t\"L\n\tModelData\x12\x0c\n\x04name\x18\x01 \x01(\x05\x12\x31\n\x05rdata\x18\x02 \x03(\x0b\x32\".thermalImagingDataCollect.RowData\"\x17\n\x07RowData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\x32\xba\x01\n ThermalImagingDataCollectService\x12\x95\x01\n\x19\x43ollectThermalImagingData\x12;.thermalImagingDataCollect.ThermalImagingDataCollectRequest\x1a\x39.thermalImagingDataCollect.ThermalImagingDataCollectReply\"\x00\x62\x06proto3')
)




_THERMALIMAGINGDATACOLLECTREQUEST = _descriptor.Descriptor(
  name='ThermalImagingDataCollectRequest',
  full_name='thermalImagingDataCollect.ThermalImagingDataCollectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='thermalImagingDataCollect.ThermalImagingDataCollectRequest.tag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=88,
)


_THERMALIMAGINGDATACOLLECTREPLY = _descriptor.Descriptor(
  name='ThermalImagingDataCollectReply',
  full_name='thermalImagingDataCollect.ThermalImagingDataCollectReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mdata', full_name='thermalImagingDataCollect.ThermalImagingDataCollectReply.mdata', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errorMessage', full_name='thermalImagingDataCollect.ThermalImagingDataCollectReply.errorMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=197,
)


_MODELDATA = _descriptor.Descriptor(
  name='ModelData',
  full_name='thermalImagingDataCollect.ModelData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='thermalImagingDataCollect.ModelData.name', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rdata', full_name='thermalImagingDataCollect.ModelData.rdata', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=275,
)


_ROWDATA = _descriptor.Descriptor(
  name='RowData',
  full_name='thermalImagingDataCollect.RowData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='thermalImagingDataCollect.RowData.data', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=300,
)

_THERMALIMAGINGDATACOLLECTREPLY.fields_by_name['mdata'].message_type = _MODELDATA
_MODELDATA.fields_by_name['rdata'].message_type = _ROWDATA
DESCRIPTOR.message_types_by_name['ThermalImagingDataCollectRequest'] = _THERMALIMAGINGDATACOLLECTREQUEST
DESCRIPTOR.message_types_by_name['ThermalImagingDataCollectReply'] = _THERMALIMAGINGDATACOLLECTREPLY
DESCRIPTOR.message_types_by_name['ModelData'] = _MODELDATA
DESCRIPTOR.message_types_by_name['RowData'] = _ROWDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ThermalImagingDataCollectRequest = _reflection.GeneratedProtocolMessageType('ThermalImagingDataCollectRequest', (_message.Message,), {
  'DESCRIPTOR' : _THERMALIMAGINGDATACOLLECTREQUEST,
  '__module__' : 'tidc_pb2'
  # @@protoc_insertion_point(class_scope:thermalImagingDataCollect.ThermalImagingDataCollectRequest)
  })
_sym_db.RegisterMessage(ThermalImagingDataCollectRequest)

ThermalImagingDataCollectReply = _reflection.GeneratedProtocolMessageType('ThermalImagingDataCollectReply', (_message.Message,), {
  'DESCRIPTOR' : _THERMALIMAGINGDATACOLLECTREPLY,
  '__module__' : 'tidc_pb2'
  # @@protoc_insertion_point(class_scope:thermalImagingDataCollect.ThermalImagingDataCollectReply)
  })
_sym_db.RegisterMessage(ThermalImagingDataCollectReply)

ModelData = _reflection.GeneratedProtocolMessageType('ModelData', (_message.Message,), {
  'DESCRIPTOR' : _MODELDATA,
  '__module__' : 'tidc_pb2'
  # @@protoc_insertion_point(class_scope:thermalImagingDataCollect.ModelData)
  })
_sym_db.RegisterMessage(ModelData)

RowData = _reflection.GeneratedProtocolMessageType('RowData', (_message.Message,), {
  'DESCRIPTOR' : _ROWDATA,
  '__module__' : 'tidc_pb2'
  # @@protoc_insertion_point(class_scope:thermalImagingDataCollect.RowData)
  })
_sym_db.RegisterMessage(RowData)



_THERMALIMAGINGDATACOLLECTSERVICE = _descriptor.ServiceDescriptor(
  name='ThermalImagingDataCollectService',
  full_name='thermalImagingDataCollect.ThermalImagingDataCollectService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=303,
  serialized_end=489,
  methods=[
  _descriptor.MethodDescriptor(
    name='CollectThermalImagingData',
    full_name='thermalImagingDataCollect.ThermalImagingDataCollectService.CollectThermalImagingData',
    index=0,
    containing_service=None,
    input_type=_THERMALIMAGINGDATACOLLECTREQUEST,
    output_type=_THERMALIMAGINGDATACOLLECTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_THERMALIMAGINGDATACOLLECTSERVICE)

DESCRIPTOR.services_by_name['ThermalImagingDataCollectService'] = _THERMALIMAGINGDATACOLLECTSERVICE

# @@protoc_insertion_point(module_scope)
