FROM dkzhang007/golang_protobuf_grpc-x86

WORKDIR /go/src

RUN git clone https://github.com/dkzhang/Robot2019.git #20191203-001

CMD go run /chassisDriverForRobot/robotMultiplePointsMove/server/server.go