// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spm.proto

package robotSinglePointMove

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SinglePointInfo struct {
	//Mask value to indicate optional value
	// marker   |   location    |    max_continuous_retries |   distance_tolerance  |   theta_tolerance
	//  16      |      8        |               4           |           2           |           1
	InfoMask uint32 `protobuf:"varint,1,opt,name=infoMask,proto3" json:"infoMask,omitempty"`
	//either marker or location
	Marker string `protobuf:"bytes,2,opt,name=marker,proto3" json:"marker,omitempty"`
	//either marker or location
	LocationX     float32 `protobuf:"fixed32,3,opt,name=locationX,proto3" json:"locationX,omitempty"`
	LocationY     float32 `protobuf:"fixed32,4,opt,name=locationY,proto3" json:"locationY,omitempty"`
	LocationTheta float32 `protobuf:"fixed32,5,opt,name=locationTheta,proto3" json:"locationTheta,omitempty"`
	//optional
	MaxContinuousRetries int32    `protobuf:"varint,6,opt,name=max_continuous_retries,json=maxContinuousRetries,proto3" json:"max_continuous_retries,omitempty"`
	DistanceTolerance    float32  `protobuf:"fixed32,7,opt,name=distance_tolerance,json=distanceTolerance,proto3" json:"distance_tolerance,omitempty"`
	ThetaTolerance       float32  `protobuf:"fixed32,8,opt,name=theta_tolerance,json=thetaTolerance,proto3" json:"theta_tolerance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SinglePointInfo) Reset()         { *m = SinglePointInfo{} }
func (m *SinglePointInfo) String() string { return proto.CompactTextString(m) }
func (*SinglePointInfo) ProtoMessage()    {}
func (*SinglePointInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_235e10e8111f85bc, []int{0}
}

func (m *SinglePointInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SinglePointInfo.Unmarshal(m, b)
}
func (m *SinglePointInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SinglePointInfo.Marshal(b, m, deterministic)
}
func (m *SinglePointInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SinglePointInfo.Merge(m, src)
}
func (m *SinglePointInfo) XXX_Size() int {
	return xxx_messageInfo_SinglePointInfo.Size(m)
}
func (m *SinglePointInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SinglePointInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SinglePointInfo proto.InternalMessageInfo

func (m *SinglePointInfo) GetInfoMask() uint32 {
	if m != nil {
		return m.InfoMask
	}
	return 0
}

func (m *SinglePointInfo) GetMarker() string {
	if m != nil {
		return m.Marker
	}
	return ""
}

func (m *SinglePointInfo) GetLocationX() float32 {
	if m != nil {
		return m.LocationX
	}
	return 0
}

func (m *SinglePointInfo) GetLocationY() float32 {
	if m != nil {
		return m.LocationY
	}
	return 0
}

func (m *SinglePointInfo) GetLocationTheta() float32 {
	if m != nil {
		return m.LocationTheta
	}
	return 0
}

func (m *SinglePointInfo) GetMaxContinuousRetries() int32 {
	if m != nil {
		return m.MaxContinuousRetries
	}
	return 0
}

func (m *SinglePointInfo) GetDistanceTolerance() float32 {
	if m != nil {
		return m.DistanceTolerance
	}
	return 0
}

func (m *SinglePointInfo) GetThetaTolerance() float32 {
	if m != nil {
		return m.ThetaTolerance
	}
	return 0
}

type MultiplePointsInfo struct {
	//Mask value to indicate optional value
	InfoMask uint32 `protobuf:"varint,1,opt,name=infoMask,proto3" json:"infoMask,omitempty"`
	//required
	Marker []string `protobuf:"bytes,2,rep,name=marker,proto3" json:"marker,omitempty"`
	//optional
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	DistanceTolerance    float32  `protobuf:"fixed32,4,opt,name=distance_tolerance,json=distanceTolerance,proto3" json:"distance_tolerance,omitempty"`
	MaxContinuousRetries float32  `protobuf:"fixed32,5,opt,name=max_continuous_retries,json=maxContinuousRetries,proto3" json:"max_continuous_retries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiplePointsInfo) Reset()         { *m = MultiplePointsInfo{} }
func (m *MultiplePointsInfo) String() string { return proto.CompactTextString(m) }
func (*MultiplePointsInfo) ProtoMessage()    {}
func (*MultiplePointsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_235e10e8111f85bc, []int{1}
}

func (m *MultiplePointsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplePointsInfo.Unmarshal(m, b)
}
func (m *MultiplePointsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplePointsInfo.Marshal(b, m, deterministic)
}
func (m *MultiplePointsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplePointsInfo.Merge(m, src)
}
func (m *MultiplePointsInfo) XXX_Size() int {
	return xxx_messageInfo_MultiplePointsInfo.Size(m)
}
func (m *MultiplePointsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplePointsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplePointsInfo proto.InternalMessageInfo

func (m *MultiplePointsInfo) GetInfoMask() uint32 {
	if m != nil {
		return m.InfoMask
	}
	return 0
}

func (m *MultiplePointsInfo) GetMarker() []string {
	if m != nil {
		return m.Marker
	}
	return nil
}

func (m *MultiplePointsInfo) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MultiplePointsInfo) GetDistanceTolerance() float32 {
	if m != nil {
		return m.DistanceTolerance
	}
	return 0
}

func (m *MultiplePointsInfo) GetMaxContinuousRetries() float32 {
	if m != nil {
		return m.MaxContinuousRetries
	}
	return 0
}

type MoveResponse struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Uuid                 uint32   `protobuf:"varint,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TaskId               uint32   `protobuf:"varint,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveResponse) Reset()         { *m = MoveResponse{} }
func (m *MoveResponse) String() string { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()    {}
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_235e10e8111f85bc, []int{2}
}

func (m *MoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResponse.Unmarshal(m, b)
}
func (m *MoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResponse.Marshal(b, m, deterministic)
}
func (m *MoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResponse.Merge(m, src)
}
func (m *MoveResponse) XXX_Size() int {
	return xxx_messageInfo_MoveResponse.Size(m)
}
func (m *MoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResponse proto.InternalMessageInfo

func (m *MoveResponse) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *MoveResponse) GetUuid() uint32 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *MoveResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MoveResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *MoveResponse) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type MoveAndWaitForArrivalResponse struct {
	ErrorMessage         string   `protobuf:"bytes,1,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveAndWaitForArrivalResponse) Reset()         { *m = MoveAndWaitForArrivalResponse{} }
func (m *MoveAndWaitForArrivalResponse) String() string { return proto.CompactTextString(m) }
func (*MoveAndWaitForArrivalResponse) ProtoMessage()    {}
func (*MoveAndWaitForArrivalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_235e10e8111f85bc, []int{3}
}

func (m *MoveAndWaitForArrivalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveAndWaitForArrivalResponse.Unmarshal(m, b)
}
func (m *MoveAndWaitForArrivalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveAndWaitForArrivalResponse.Marshal(b, m, deterministic)
}
func (m *MoveAndWaitForArrivalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveAndWaitForArrivalResponse.Merge(m, src)
}
func (m *MoveAndWaitForArrivalResponse) XXX_Size() int {
	return xxx_messageInfo_MoveAndWaitForArrivalResponse.Size(m)
}
func (m *MoveAndWaitForArrivalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveAndWaitForArrivalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveAndWaitForArrivalResponse proto.InternalMessageInfo

func (m *MoveAndWaitForArrivalResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*SinglePointInfo)(nil), "robotSinglePointMove.SinglePointInfo")
	proto.RegisterType((*MultiplePointsInfo)(nil), "robotSinglePointMove.MultiplePointsInfo")
	proto.RegisterType((*MoveResponse)(nil), "robotSinglePointMove.MoveResponse")
	proto.RegisterType((*MoveAndWaitForArrivalResponse)(nil), "robotSinglePointMove.MoveAndWaitForArrivalResponse")
}

func init() { proto.RegisterFile("spm.proto", fileDescriptor_235e10e8111f85bc) }

var fileDescriptor_235e10e8111f85bc = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x5b, 0x6a, 0xdb, 0x40,
	0x14, 0x8d, 0x1c, 0x3f, 0xa2, 0x4b, 0xd4, 0xd0, 0x8b, 0x9b, 0x8a, 0xd0, 0x82, 0x51, 0x5b, 0xea,
	0x9f, 0xfa, 0xa3, 0xe9, 0x06, 0x42, 0xa0, 0x90, 0x0f, 0x43, 0x99, 0x04, 0xda, 0x7c, 0x89, 0x89,
	0x34, 0x49, 0x07, 0x4b, 0x73, 0xcd, 0x3c, 0x82, 0xd7, 0xd1, 0xbd, 0x74, 0x05, 0x5d, 0x47, 0xf7,
	0x52, 0x34, 0xb2, 0x5d, 0xa9, 0x48, 0xd0, 0x7c, 0x79, 0xce, 0x83, 0xb9, 0xc7, 0x47, 0x73, 0x21,
	0x34, 0xeb, 0x72, 0xb1, 0xd6, 0x64, 0x09, 0xa7, 0x9a, 0xee, 0xc8, 0x5e, 0x4b, 0xf5, 0x50, 0x88,
	0x2f, 0x24, 0x95, 0x5d, 0xd2, 0xa3, 0x48, 0x7e, 0x0e, 0xe0, 0xa4, 0xc1, 0x5d, 0xa9, 0x7b, 0xc2,
	0x33, 0x38, 0x92, 0xea, 0x9e, 0x96, 0xdc, 0xac, 0xe2, 0x60, 0x16, 0xcc, 0x23, 0xb6, 0xc7, 0x78,
	0x0a, 0xe3, 0x92, 0xeb, 0x95, 0xd0, 0xf1, 0x60, 0x16, 0xcc, 0x43, 0xb6, 0x45, 0xf8, 0x0a, 0xc2,
	0x82, 0x32, 0x6e, 0x25, 0xa9, 0x6f, 0xf1, 0xe1, 0x2c, 0x98, 0x0f, 0xd8, 0x5f, 0xa2, 0xa9, 0xde,
	0xc6, 0xc3, 0xb6, 0x7a, 0x8b, 0x6f, 0x21, 0xda, 0x81, 0x9b, 0xef, 0xc2, 0xf2, 0x78, 0xe4, 0x1d,
	0x6d, 0x12, 0x3f, 0xc1, 0x69, 0xc9, 0x37, 0x69, 0x46, 0xca, 0x4a, 0xe5, 0xc8, 0x99, 0x54, 0x0b,
	0xab, 0xa5, 0x30, 0xf1, 0x78, 0x16, 0xcc, 0x47, 0x6c, 0x5a, 0xf2, 0xcd, 0xe5, 0x5e, 0x64, 0xb5,
	0x86, 0x1f, 0x00, 0x73, 0x69, 0x2c, 0x57, 0x99, 0x48, 0x2d, 0x15, 0x42, 0x57, 0xa7, 0x78, 0xe2,
	0x07, 0x3c, 0xdf, 0x29, 0x37, 0x3b, 0x01, 0xdf, 0xc3, 0x89, 0xad, 0xa6, 0x35, 0xbc, 0x47, 0xde,
	0xfb, 0xcc, 0xd3, 0x7b, 0x63, 0xf2, 0x2b, 0x00, 0x5c, 0xba, 0xc2, 0xca, 0xf5, 0xb6, 0x39, 0xf3,
	0xa4, 0xea, 0x0e, 0x1b, 0xd5, 0x4d, 0x61, 0x94, 0x91, 0x53, 0xd6, 0xd7, 0x36, 0x62, 0x35, 0xe8,
	0x09, 0x3e, 0xec, 0x0b, 0xde, 0xdf, 0x4e, 0x5d, 0x66, 0x67, 0x3b, 0xc9, 0x8f, 0x00, 0x8e, 0xab,
	0x67, 0xc0, 0x84, 0x59, 0x93, 0x32, 0x02, 0x63, 0x98, 0x64, 0x54, 0x96, 0x5c, 0xe5, 0x3e, 0x7e,
	0xc8, 0x76, 0x10, 0x11, 0x86, 0xce, 0xc9, 0xdc, 0x7f, 0xf6, 0x88, 0xf9, 0x73, 0xf5, 0x8f, 0x8c,
	0xe5, 0xd6, 0x19, 0x1f, 0x3d, 0x64, 0x5b, 0x84, 0x6f, 0x20, 0x12, 0x5a, 0x93, 0x4e, 0x4b, 0x61,
	0x0c, 0x7f, 0xa8, 0x63, 0x87, 0xec, 0xd8, 0x93, 0xcb, 0x9a, 0xc3, 0x97, 0x30, 0xb1, 0xdc, 0xac,
	0x52, 0x99, 0xfb, 0x88, 0x11, 0x1b, 0x57, 0xf0, 0x2a, 0x4f, 0x2e, 0xe1, 0x75, 0x95, 0xe9, 0x42,
	0xe5, 0x5f, 0xb9, 0xb4, 0x9f, 0x49, 0x5f, 0x68, 0x2d, 0x1f, 0x79, 0xb1, 0x0f, 0x99, 0x40, 0xeb,
	0xa6, 0x6d, 0xd2, 0x16, 0xf7, 0xf1, 0x77, 0xd0, 0x7a, 0xd7, 0xd5, 0x85, 0x78, 0x0d, 0x43, 0xff,
	0xfb, 0x6e, 0xd1, 0xb5, 0x0a, 0x8b, 0x7f, 0xd6, 0xe0, 0x2c, 0xe9, 0xb6, 0x35, 0xfb, 0x4a, 0x0e,
	0xd0, 0xc1, 0x8b, 0xce, 0xb4, 0xff, 0x3b, 0xe5, 0xbc, 0x7f, 0x4a, 0x6f, 0x03, 0xc9, 0xc1, 0xdd,
	0xd8, 0x2f, 0xf5, 0xf9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x1f, 0xfa, 0x4c, 0xe1, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SinglePointMoveClient is the client API for SinglePointMove service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SinglePointMoveClient interface {
	Move(ctx context.Context, in *SinglePointInfo, opts ...grpc.CallOption) (*MoveResponse, error)
	MoveAndWaitForArrival(ctx context.Context, in *SinglePointInfo, opts ...grpc.CallOption) (*MoveAndWaitForArrivalResponse, error)
}

type singlePointMoveClient struct {
	cc *grpc.ClientConn
}

func NewSinglePointMoveClient(cc *grpc.ClientConn) SinglePointMoveClient {
	return &singlePointMoveClient{cc}
}

func (c *singlePointMoveClient) Move(ctx context.Context, in *SinglePointInfo, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/robotSinglePointMove.SinglePointMove/Move", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *singlePointMoveClient) MoveAndWaitForArrival(ctx context.Context, in *SinglePointInfo, opts ...grpc.CallOption) (*MoveAndWaitForArrivalResponse, error) {
	out := new(MoveAndWaitForArrivalResponse)
	err := c.cc.Invoke(ctx, "/robotSinglePointMove.SinglePointMove/MoveAndWaitForArrival", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SinglePointMoveServer is the server API for SinglePointMove service.
type SinglePointMoveServer interface {
	Move(context.Context, *SinglePointInfo) (*MoveResponse, error)
	MoveAndWaitForArrival(context.Context, *SinglePointInfo) (*MoveAndWaitForArrivalResponse, error)
}

// UnimplementedSinglePointMoveServer can be embedded to have forward compatible implementations.
type UnimplementedSinglePointMoveServer struct {
}

func (*UnimplementedSinglePointMoveServer) Move(ctx context.Context, req *SinglePointInfo) (*MoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Move not implemented")
}
func (*UnimplementedSinglePointMoveServer) MoveAndWaitForArrival(ctx context.Context, req *SinglePointInfo) (*MoveAndWaitForArrivalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveAndWaitForArrival not implemented")
}

func RegisterSinglePointMoveServer(s *grpc.Server, srv SinglePointMoveServer) {
	s.RegisterService(&_SinglePointMove_serviceDesc, srv)
}

func _SinglePointMove_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SinglePointInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinglePointMoveServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/robotSinglePointMove.SinglePointMove/Move",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinglePointMoveServer).Move(ctx, req.(*SinglePointInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinglePointMove_MoveAndWaitForArrival_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SinglePointInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinglePointMoveServer).MoveAndWaitForArrival(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/robotSinglePointMove.SinglePointMove/MoveAndWaitForArrival",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinglePointMoveServer).MoveAndWaitForArrival(ctx, req.(*SinglePointInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _SinglePointMove_serviceDesc = grpc.ServiceDesc{
	ServiceName: "robotSinglePointMove.SinglePointMove",
	HandlerType: (*SinglePointMoveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Move",
			Handler:    _SinglePointMove_Move_Handler,
		},
		{
			MethodName: "MoveAndWaitForArrival",
			Handler:    _SinglePointMove_MoveAndWaitForArrival_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spm.proto",
}
