# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tir.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tir.proto',
  package='thermalImagingRendering',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ttir.proto\x12\x17thermalImagingRendering\"v\n\x1eThermalImagingRenderingRequest\x12\x11\n\tdataArray\x18\x01 \x03(\x01\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x10\n\x08\x66ilepath\x18\x04 \x01(\t\x12\x10\n\x08\x66ilename\x18\x05 \x01(\t\"4\n\x1cThermalImagingRenderingReply\x12\x14\n\x0c\x65rrorMessage\x18\x01 \x01(\t2\xab\x01\n\x1eThermalImagingRenderingService\x12\x88\x01\n\x14ThermalImagingRender\x12\x37.thermalImagingRendering.ThermalImagingRenderingRequest\x1a\x35.thermalImagingRendering.ThermalImagingRenderingReply\"\x00\x62\x06proto3')
)




_THERMALIMAGINGRENDERINGREQUEST = _descriptor.Descriptor(
  name='ThermalImagingRenderingRequest',
  full_name='thermalImagingRendering.ThermalImagingRenderingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataArray', full_name='thermalImagingRendering.ThermalImagingRenderingRequest.dataArray', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='thermalImagingRendering.ThermalImagingRenderingRequest.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='thermalImagingRendering.ThermalImagingRenderingRequest.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filepath', full_name='thermalImagingRendering.ThermalImagingRenderingRequest.filepath', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='thermalImagingRendering.ThermalImagingRenderingRequest.filename', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=156,
)


_THERMALIMAGINGRENDERINGREPLY = _descriptor.Descriptor(
  name='ThermalImagingRenderingReply',
  full_name='thermalImagingRendering.ThermalImagingRenderingReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errorMessage', full_name='thermalImagingRendering.ThermalImagingRenderingReply.errorMessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=210,
)

DESCRIPTOR.message_types_by_name['ThermalImagingRenderingRequest'] = _THERMALIMAGINGRENDERINGREQUEST
DESCRIPTOR.message_types_by_name['ThermalImagingRenderingReply'] = _THERMALIMAGINGRENDERINGREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ThermalImagingRenderingRequest = _reflection.GeneratedProtocolMessageType('ThermalImagingRenderingRequest', (_message.Message,), {
  'DESCRIPTOR' : _THERMALIMAGINGRENDERINGREQUEST,
  '__module__' : 'tir_pb2'
  # @@protoc_insertion_point(class_scope:thermalImagingRendering.ThermalImagingRenderingRequest)
  })
_sym_db.RegisterMessage(ThermalImagingRenderingRequest)

ThermalImagingRenderingReply = _reflection.GeneratedProtocolMessageType('ThermalImagingRenderingReply', (_message.Message,), {
  'DESCRIPTOR' : _THERMALIMAGINGRENDERINGREPLY,
  '__module__' : 'tir_pb2'
  # @@protoc_insertion_point(class_scope:thermalImagingRendering.ThermalImagingRenderingReply)
  })
_sym_db.RegisterMessage(ThermalImagingRenderingReply)



_THERMALIMAGINGRENDERINGSERVICE = _descriptor.ServiceDescriptor(
  name='ThermalImagingRenderingService',
  full_name='thermalImagingRendering.ThermalImagingRenderingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=213,
  serialized_end=384,
  methods=[
  _descriptor.MethodDescriptor(
    name='ThermalImagingRender',
    full_name='thermalImagingRendering.ThermalImagingRenderingService.ThermalImagingRender',
    index=0,
    containing_service=None,
    input_type=_THERMALIMAGINGRENDERINGREQUEST,
    output_type=_THERMALIMAGINGRENDERINGREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_THERMALIMAGINGRENDERINGSERVICE)

DESCRIPTOR.services_by_name['ThermalImagingRenderingService'] = _THERMALIMAGINGRENDERINGSERVICE

# @@protoc_insertion_point(module_scope)
